[package]
name = "learn_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.23", features = ["derive"] }
patharg = "0.4.0"
rand = "0.8.5"
rand_distr = "0.4.3"
regex = "1.11.1"
termsize = "0.1.9"
